import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  isLoaded,
} from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "sonner";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      afterSignOutUrl="/"
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} flex h-screen flex-col antialiased`}
        >
          <Toaster richColors visibleToasts={1} />
          <header>
            <Navbar />
          </header>
          <main className="h-full">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
